version: '3.8'

services:
  backend:
    image: my-backend-image:latest
    ports:
      - "8081:8082"  # Map host port 8081 to container port 8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:

  frontend:
    image: my-frontend-image:latest
    ports:
      - "80:80"  # Map host port 80 to container port 80

  mysql:
    image: mysql:5.7
    ports:
      - "3333:3306"  # Map host port 3333 to container port 3306
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=devops
